[secret]
api_token_path = "apitoken"

[db]
host = "challenge_db" # change to "localhost" for non docker run in local
port = 5432
user = "postgres"
password = "postgres123"
db_name = "challenge"
ssl_mode = "disable"
time_zone = "Asia/Singapore"
